title: Juseong Park
description: Juseong Park - Senior Engineer at Qualcomm Wireless R&D, with a Ph.D. in ECE from UT Austin. Research in wireless communications, signal processing, and machine learning.
last_updated: 2026-09-09
url: "https://ju-seong.github.io"
baseurl: ""
timezone: America/Chicago
markdown: kramdown
permalink: pretty
