title: Juseong Park
description: Juseong Park - Ph.D. Candidate and researcher in wireless communications and machine learning
url: "https://ju-seong.github.io"
baseurl: ""
timezone: America/Chicago
markdown: kramdown
permalink: pretty
